### ISSUE TITLE
Is this still a viable option?

### ISSUE THREAD

**Issue by mbonne** [kai-h/vpn-mobileconfig-generator#1]
Hi Kai,

Is this still a good option? considering the recent release of Apple Configurator now doesn't let me set the shared secret within the profile...

Miro.

**Comment by kai-h** [comment]
Hi Miro,

Yes, it works for me for quickly generating profiles outside of Profile Manager or Configurator. It’s very quick if I need to set up a bunch of computers all with their own VPN config. Take note though that there is minimal error checking, I assume the end user knows what they’re doing and puts the correct parameters in to the script.

In the weeks leading up to the COVID lockdown, we would have set up over 100 users with VPN configs, and this is what we used to generate the profiles.

It generates random GUIDs each time you run it, so this means that if you update your VPN settings and build a new profile with this script, the Mac will see it as a completely new profile, not an update to the previously installed one. It also puts the Shared Secret into the profile in plaintext, whereas Profile Manager encodes them as Base64. While Base64 isn’t really encryption, it does stop someone from reading the shared secret in a basic text editor.
